### ISSUE TITLE
Manually define paths for Source Ports

### ISSUE THREAD

**Issue by OpenRift412** [fgsfds/BuildLauncher#10]
I can see a lot of potential in this launcher, but there are a few things that hold it back from being perfect. One of those things would be letting users define paths to source ports they already have installed. By now, lots of build engine fans already have their own structures set up for their source ports, so I think it would be wise to let users set the paths to those source ports as well as read the mods that are installed there if possible so that they may be added to the campaigns list.

**Comment by fgsfds** [comment]
I got another idea. You will be able to add you own ports and then run addons with them. Downloadable ports will remain the same.

![{F7F3BDEF-54B0-426F-A674-F226660446C0}](https://github.com/user-attachments/assets/e40267b1-3d6f-4edf-8195-555555c81640)

![{B62CB544-C952-41E2-8314-23E5E1E776DC}](https://github.com/user-attachments/assets/1a9dc865-30a3-4e41-9b49-1f5219615584)

**Comment by fgsfds** [comment]
Added in https://github.com/fgsfds/BuildLauncher/releases/tag/0.25.0
