### ISSUE TITLE
Sorting by size is incorrect

### ISSUE THREAD

**Issue by Mancubuss** [fgsfds/BuildLauncher#14]
When I press on the 'Size' column header in GAME/Downloads, the column gets sorted, but the sorting seems to be done by string value and not the actual size. Also, as I am too lazy to raise a separate issue for that, the size is in Kilo/MegaBITS, and not BYTES.

**Comment by fgsfds** [comment]
Fixed in https://github.com/fgsfds/BuildLauncher/releases/tag/0.25.1
