### ISSUE TITLE
Configuration Window

### ISSUE THREAD

**Issue by StardustX7** [fgsfds/BuildLauncher#2]
Windows 11 x64
When I launch eduke32 or rednukem for the first time, I got the configuration window, but after that it always skip it, even if I toggle the option to have it on every launch

Thanks a lot for your great work.

**Comment by fgsfds** [comment]
That's intentional. Ideally, you shouldn't even see it the first time. Do people actually need this startup window?

**Comment by StardustX7** [comment]
I personaly think it s useful to manage some options before launching a game

If you want a concrete example
If you launch Duke 3D with rednukem with polymer rendering on, you play,  and then quit the game
Later you decide to play Duke 64, you launch it and you don t have the opportunity to switch to another rendering mode, so the game launch and is visually corrupted, unplayable cause incompatible with polymer
You have to quit it, launch duke 3D again to switch rendering mode or go to the port folder and launch the executable manually to uncheck polymer
Quite a mess

Correct me if I'm wrong but there is no option to configure those options directly in the frontend before launching a game or to launch the configuration tool via the frontend ? I searched for those kind of options but did not find anything.

**Comment by fgsfds** [comment]
I see. I'll add "skip launcher" checkbox in the next version.

**Comment by StardustX7** [comment]
Nice, thanks a lot

I really appreciate your work, can't wait to see it expand

**Comment by fgsfds** [comment]
Added https://github.com/fgsfds/BuildLauncher/commit/e047a33bce70b4c53d496b7100d8a9239fead555

**Comment by fgsfds** [comment]
It's not supported by Raze though, it always skips startup window when you launch the game from cmd. Can't do anything about it.

**Comment by StardustX7** [comment]
Thanks a lot ^^

It's unfortunate for raze but I hope it will be possible to launch DC and caribbean with eduke or rednukem via the frontend in the future
