### ISSUE TITLE
Directories settings seems to be messed up

### ISSUE THREAD

**Issue by StardustX7** [fgsfds/BuildLauncher#3]
In the latest release 0.60 the directories settings for each gam seems to be at the wrong place, for exemple the blood directory line ask me to select a z64 rom so I suppose it is in fact the Duke 64 line, all lines seems messed up in the same way

![Capture d'écran 2024-03-20 132333](https://github.com/fgsfds/BuildLauncher/assets/54170830/3db05d19-8b5d-466f-8a93-e9f3137ce5d6)

**Comment by fgsfds** [comment]
Fixed, thanks https://github.com/fgsfds/BuildLauncher/releases/tag/0.6.1
